### ISSUE TITLE
Add ability to change which icon to dispay

### ISSUE THREAD

**Issue by andreyorst** [divinae/uswitch#4]
Displaying a settings icon in the panel should mean something which is connected with system settings. Your applet containes such menu entry, but it is not main function of this applet, so displaying a settings icon is quite unnecessarily. You could use an `avatar-default-symbolic` for such a thing, But i think that adding an option to choose icon for applet, wil be a lot more efficient

**Comment by divinae** [comment]
done - please check it

**Comment by andreyorst** [comment]
Everything works great
